# Generated by Django 4.0.4 on 2022-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last_name')),
                ('birthday_year', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
            ],
        ),
    ]
